#!/usr/bin/env python3
"""Generate random atomic chess positions and their legal moves via Fairy-Stockfish."""

import subprocess
import random
import re
import sys

STOCKFISH = "/workspace/atomic_movegen/Fairy-Stockfish/src/stockfish"
OUTPUT = "tests/moves.md"

def read_until(proc, marker, timeout=5):
    """Read lines from proc.stdout until we see a line containing `marker`."""
    lines = []
    for line in iter(proc.stdout.readline, ""):
        lines.append(line)
        if marker in line:
            break
    return lines

def send(proc, cmd):
    proc.stdin.write(cmd + "\n")
    proc.stdin.flush()

def parse_perft_moves(lines):
    """Parse `go perft 1` output into a list of legal move strings."""
    moves = []
    for line in lines:
        line = line.strip()
        # Matches "e2e4: 20" (or any move like "a7a8q": 1)
        m = re.match(r'^([a-h][1-8][a-h][1-8][nbrqNBRQ]?):\s*\d+$', line)
        if m:
            moves.append(m.group(1))
    return moves

def parse_fen(lines):
    """Extract the FEN string from `d` output."""
    for line in lines:
        if line.startswith("Fen:"):
            return line[len("Fen:"):].strip()
    return None

def start_engine():
    proc = subprocess.Popen(
        [STOCKFISH],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        universal_newlines=True,
        bufsize=1,
    )
    send(proc, "uci")
    read_until(proc, "uciok")
    send(proc, "setoption name UCI_Variant value atomic")
    send(proc, "isready")
    read_until(proc, "readyok")
    return proc

def get_fen(proc):
    send(proc, "d")
    out = read_until(proc, "Checkers:")
    # Also keep reading until we see the Fen: line
    # The 'd' output ends with Checkers:, Fen:, then Key: lines
    # Actually let's just read extra lines
    fen = None
    for line in out:
        if line.startswith("Fen:"):
            fen = line[len("Fen:"):].strip()
    if fen is None:
        # Read a few more lines
        for _ in range(5):
            line = proc.stdout.readline()
            if line.startswith("Fen:"):
                fen = line[len("Fen:"):].strip()
                break
    return fen

def main():
    random.seed()
    proc = start_engine()
    entries = []
    seen_fens = set()

    while len(entries) < 20:
        # Start fresh game
        send(proc, "position startpos")
        move_stack = []
        ply = 0

        while len(entries) < 20:
            # Get legal moves
            send(proc, "go perft 1")
            out = read_until(proc, "Nodes searched:")
            legal = parse_perft_moves(out)

            if not legal:
                # Game over (king captured, checkmate, stalemate, etc.)
                break

            # Record at every 7th ply
            if ply % 7 == 0:
                fen = get_fen(proc)
                if fen and fen not in seen_fens:
                    seen_fens.add(fen)
                    entries.append((fen, sorted(legal)))
                    print(f"[{len(entries)}/20] Ply {ply}: {fen}")
                    sys.stdout.flush()
                    if len(entries) >= 20:
                        break

            # Pick a random move and play it
            move = random.choice(legal)
            move_stack.append(move)
            send(proc, f"position startpos moves {' '.join(move_stack)}")
            ply += 1

    proc.terminate()

    # Write markdown table
    header = "# Atomic Chess Positions with Legal Moves\n\n"
    header += "Generated by Fairy-Stockfish by simulating random atomic games.\n"
    header += "Records FEN at every 7th ply (20 positions).\n\n"

    header += "| # | FEN | Legal Moves |\n"
    header += "|---|-----|-------------|\n"

    rows = []
    for i, (fen, moves) in enumerate(entries, 1):
        moves_str = " ".join(moves)
        rows.append(f"| {i} | `{fen}` | {moves_str} |")

    with open(OUTPUT, "w") as f:
        f.write(header)
        f.write("\n".join(rows))
        f.write("\n")

    print(f"\nWrote {len(entries)} entries to {OUTPUT}")

if __name__ == "__main__":
    main()
